# Generated by Django 5.1.3 on 2024-11-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                ("enrollment_date", models.DateField(verbose_name="Дата зачисления")),
                ("faculty", models.CharField(max_length=100, verbose_name="Факультет")),
            ],
        ),
    ]
