# Generated by Django 5.1.3 on 2024-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                ("dob", models.DateField(verbose_name="Дата рождения")),
                (
                    "registration_date",
                    models.DateField(verbose_name="Дата регистрации"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StudentProfile",
        ),
    ]
